adduct_settings:
  adduct_ppm_diff: 10
  adduct_rt_diff: 5
adducts:
  -H2O: -18.01056
  K+: 37.95588
  Na+: 21.98194
fdr:
  keep_complement: false
  min_distance: 1
  n_permutations: 1000
  seed: 42
  sweep:
    filter.present_ratio:
    - 0.5
    - 0.8
    - 1.0
filter:
  present_ratio: 0.6
preprocessing:
  mass_trace_ppm: 8
  max_ppm_diff_combine_features: 10
  max_rt_diff_combine_features: 40
  noise_threshold: 10000
  remove_single_traces: 'false'
unique:
  OE_LFC_to_WT: 2
  WT_LFC_to_KO: 6
  allow_KO_detection: false
  model_OE_LFC: false
visual_inspection:
  RT_window: 120
  ppm_error: 10
